### ISSUE TITLE
Most important issues for first basic release and further promotion

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#31]
When these issues are fixed, I’d say the app can be promoted further like on the user at owncloud mailinglist, Twitter etc and be put on F-Droid. :)

* [x] Problems during log in process #21 / Autoload notes list on first connection #32
* [ ] Make note directly editable #3
* [ ] Line breaks ignored #24
* [x] New note gets sorted all the way down in the list #30
* [x] Autosave #26

What do you think @stefan-niedermann @davivel @tobiasKaminsky @AndyScherzinger @Stoyicker @Kernald @LukeOwncloud?

@stefan-niedermann maybe create a milestone here on Github for »0.1« – that helps a lot with development planning and prioritization. :)

**Comment by stefan-niedermann** [comment]
> @stefan-niedermann maybe create a milestone here on Github for »0.1« – that helps a lot with development planning and prioritization. :)

I'm already working with milestones to categorize issues. Let's mark 0.5.0 as "ready-for-community-test-milestone" :)
about "Make note directly editable": this one is a *really, really* big ticket. this means very much implementation effort and i currently have no idea how to realize this in a smart way. Are you sure you want to wait for this issue? since i don't have very much time i'm not sure if i get this issue fixed within the next weeks or even months. it's easy to close small issues when i have some hours, but this one would required to work on it for longer time.

the other ones are valid from my point of view :+1:

**Comment by jancborchardt** [comment]
Ok, then let’s first go for the other ones.

I really do think the »Make note directly editable« is very important for a notes app which gets out of your way, but if you say it will take a _lot_ of work then of course we can postpone that and promote already before that. And hopefully someone of @kernald @stoyicker @andyscherzinger @tobiaskaminsky @lukeowncloud @masensio or @davivel can help. :)

**Comment by jancborchardt** [comment]
@stefan-niedermann awesome to see the activity on the app again! :) Only 2 issues left!

**Comment by jancborchardt** [comment]
Oh and @stefan-niedermann, is there an updated apk?

**Comment by stefan-niedermann** [comment]
Remove milestone because it's blocking other development. If i have a creative idea how to solve the two remaining issues i will do it. Maybe we can close this issue as well, since we have a separate issue for #3 and #24?

**Comment by jancborchardt** [comment]
Ok, I guess we can close this. But it would be good to add the 0.6.0 milestone to #3 and #24.

Also, those need proper fixes rather than creative solutions. ;) And again, both issues there stem from the Markdown plugin.
